apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire.agent" . }}-config

data:
  agent.conf: |
    agent {
      data_dir = "/run/spire"
      log_level = "INFO"

      server_address = "{{ include "spire.fqdn" . }}"
      server_port = "{{ .Values.server.port }}"
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "{{ .Release.Name }}"
        }
      }

      KeyManager "memory" {}
    }