apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "spire.agent" . }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "spire.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        {{- include "spire.labels" . | nindent 8 }}
        app.kubernetes.io/component: agent
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/agent-configmap.yaml") . | sha256sum }}
        {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.agent.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "spire.agentServiceAccountName" . }}
      automountServiceAccountToken: {{ .Values.agent.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.agent.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: spire-agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          args:
            - "-config"
            - "/run/spire/config/agent.conf"
          {{- if .Values.agent.probes.enabled }}
          readinessProbe:
            exec:
              command: ["/opt/spire/bin/spire-agent", "healthcheck"]
            periodSeconds: {{ .Values.agent.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.agent.probes.readiness.timeoutSeconds }}
          livenessProbe:
            exec:
              command: ["/opt/spire/bin/spire-agent", "healthcheck"]
            periodSeconds: {{ .Values.agent.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.agent.probes.liveness.timeoutSeconds }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /run/spire/config
            - name: socket
              mountPath: /run/spire/sockets
          securityContext:
            {{- toYaml .Values.agent.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "spire.agent" . }}-config
        - name: socket
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
