{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "spire.server" . }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  podSelector:
    matchLabels:
      {{- include "spire.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- if .Values.networkPolicy.serverIngress }}
        {{- toYaml .Values.networkPolicy.serverIngress | nindent 8 }}
        {{- else }}
        - podSelector:
            matchLabels:
              {{- include "spire.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: agent
        {{- end }}
      ports:
        - port: {{ .Values.server.port }}
          protocol: TCP
  egress:
    {{- if .Values.networkPolicy.allowDns }}
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- end }}
    {{- with .Values.networkPolicy.serverEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "spire.agent" . }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  podSelector:
    matchLabels:
      {{- include "spire.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "spire.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: server
      ports:
        - port: {{ .Values.server.port }}
          protocol: TCP
    {{- if .Values.networkPolicy.allowDns }}
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- end }}
    {{- with .Values.networkPolicy.agentEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
