apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire.server" . }}-config
  labels:
    {{- include "spire.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  server.conf: |
    server {
      bind_address = "0.0.0.0"
      bind_port = "{{ .Values.server.port }}"
      trust_domain = "{{ .Values.trustDomain }}"
      data_dir = "/run/spire/data"
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "postgres"
          connection_string = "host={{ .Values.storage.postgres.host }} \
            port={{ .Values.storage.postgres.port }} \
            dbname={{ .Values.storage.postgres.db }} \
            user={{ .Values.storage.postgres.user }} \
            {{- if .Values.storage.postgres.existingSecret.name }}
            password=${SPIRE_POSTGRES_PASSWORD} \
            {{- else if .Values.storage.postgres.password }}
            password={{ .Values.storage.postgres.password }} \
            {{- end }}
            sslmode={{ .Values.storage.postgres.sslmode }}"
        }
      }

      NodeAttestor "k8s_psat" {
        plugin_data {
          clusters = {
            "{{ .Release.Name }}" = {}
          }
        }
      }

      KeyManager "memory" {}
    }
