apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ include "spire.server" . }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  serviceName: {{ include "spire.server" . }}
  replicas: {{ .Values.server.replicas }}

  selector:
    matchLabels:
      {{- include "spire.server.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "spire.server.selectorLabels" . | nindent 8 }}
        {{- with .Values.server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/server-configmap.yaml") . | sha256sum }}
        {{- with .Values.server.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "spire.server.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.server.serviceAccount.automountServiceAccountToken }}

      {{- if .Values.server.priorityClassName }}
      priorityClassName: {{ .Values.server.priorityClassName }}
      {{- end }}

      {{- with .Values.server.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.server.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: spire-server
          image: "{{ .Values.server.image }}:{{ .Values.server.tag }}"
          imagePullPolicy: {{ .Values.server.pullPolicy }}

          args:
            - "-config"
            - "/run/spire/config/server.conf"

          ports:
            - name: grpc
              containerPort: {{ .Values.server.port }}
              protocol: TCP

          env:
            {{- if .Values.storage.postgres.existingSecret }}
            - name: SPIRE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.postgres.existingSecret }}
                  key: {{ .Values.storage.postgres.existingSecretPasswordKey }}
            {{- end }}

          securityContext:
            {{- toYaml .Values.server.containerSecurityContext | nindent 12 }}

          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}

          volumeMounts:
            - name: config
              mountPath: /run/spire/config
              readOnly: true
            - name: data
              mountPath: /run/spire/data

          {{- if .Values.server.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}
            tcpSocket:
              port: grpc
          {{- end }}

          {{- if .Values.server.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}
            tcpSocket:
              port: grpc
          {{- end }}

      volumes:
        - name: config
          configMap:
            name: {{ include "spire.server" . }}-config

  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "spire.server.selectorLabels" . | nindent 10 }}
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storage.class }}
        storageClassName: {{ .Values.storage.class }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}