apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "spire.server.name" . }}

spec:
  serviceName: {{ include "spire.server.name" . }}
  replicas: 1

  selector:
    matchLabels:
      app: {{ include "spire.server.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "spire.server.name" . }}

    spec:
      serviceAccountName: {{ .Values.serviceAccount.server }}

      containers:
        - name: server
          image: "{{ .Values.server.image }}:{{ .Values.server.tag }}"
          imagePullPolicy: IfNotPresent

          args:
            - "-config"
            - "/run/spire/config/server.conf"

          ports:
            - containerPort: {{ .Values.server.port }}

          volumeMounts:
            - name: config
              mountPath: /run/spire/config

            - name: data
              mountPath: /run/spire/data

            - name: tls
              mountPath: /certs
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: {{ include "spire.server.name" . }}-config

        - name: tls
          secret:
            secretName: {{ include "spire.server.name" . }}-tls

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.server.storageSize }}