apiVersion: v1
kind: Service
metadata:
  name: {{ include "spire.server" . }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.server.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "spire.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: grpc
      port: {{ .Values.server.port }}
      targetPort: grpc
