{{- if .Values.server.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "spire.server" . }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.server.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.server.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.server.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.server.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spire.server.selectorLabels" . | nindent 6 }}
{{- end }}
