apiVersion: v1
kind: Service
metadata:
  name: {{ include "spire.server" . }}

spec:
  selector:
    app: {{ include "spire.server" . }}

  ports:
    - name: api
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}