apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.server }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.agent }}
  namespace: {{ .Release.Namespace }}