apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openbao.fullname" . }}-config
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  openbao.hcl: |
    ui = {{ .Values.config.ui }}

    api_addr = "{{ ternary "https" "http" .Values.tls.enabled }}://{{ include "openbao.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}"

    cluster_addr = "{{ ternary "https" "http" .Values.tls.enabled }}://$(POD_NAME).{{ include "openbao.headlessServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.clusterPort }}"

    listener "tcp" {
      address         = "0.0.0.0:{{ .Values.service.port }}"
      cluster_address = "0.0.0.0:{{ .Values.service.clusterPort }}"
      {{- if .Values.tls.enabled }}
      tls_disable     = 0
      tls_cert_file   = "/etc/openbao/tls/{{ .Values.tls.certFile }}"
      tls_key_file    = "/etc/openbao/tls/{{ .Values.tls.keyFile }}"
      tls_client_ca_file = "/etc/openbao/tls/{{ .Values.tls.caFile }}"
      {{- else }}
      tls_disable     = 1
      {{- end }}
    }

    storage "raft" {
      path = "/openbao/data"
    }

    service_registration "kubernetes" {
      namespace = "{{ .Release.Namespace }}"
    }
{{- with .Values.config.extraConfig }}
{{ . | nindent 4 }}
{{- end }}
