apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Release.Name }}-config

data:
  openbao.hcl: |
    ui = true
    
    api_addr = "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:8200"
    
    cluster_addr = "http://{{ .Release.Name }}-0.{{ .Release.Name }}-headless:8201"
    
    listener "tcp" {
      address         = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable     = 1
    }

    storage "raft" {
      path = "/openbao/data"
    }

    service_registration "kubernetes" {
      namespace = "{{ .Release.Namespace }}"
    }