apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openbao-k8s-auth
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]

  - apiGroups: [""]
    resources:
      - pods
      - pods/status
      - namespaces
      - services
      - nodes
    verbs:
      - get
      - list
      - watch