apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbao.headlessServiceName" . }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "openbao.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
    - name: cluster
      port: {{ .Values.service.clusterPort }}
      targetPort: cluster
