{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openbao.fullname" . }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  podSelector:
    matchLabels:
      {{- include "openbao.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- if .Values.networkPolicy.ingress }}
        {{- toYaml .Values.networkPolicy.ingress | nindent 8 }}
        {{- else }}
        - podSelector: {}
        {{- end }}
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
        - port: {{ .Values.service.clusterPort }}
          protocol: TCP
  egress:
    {{- if .Values.networkPolicy.allowDns }}
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- end }}
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
